spring:
  application:
    name: product-management-domagoj-borovcak

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: "127.0.0.1:29092"

product-management:
  clients:
    hnb-api:
      currency-usd-url: https://api.hnb.hr/tecajn-eur/v3?valuta=USD

  schedulers:
    hnb-cache-refresher:
      enabled: true
      cron: 0 0 * * * *

  kafka:
    products-topic: products